### PR TITLE
Fix `commute_ppr` and `merge_ppr_ppm` to handle nullary operations correctly when sorting.

### LINKED ISSUE #2194: `sortTopologically` incorrectly moves nullary operations (Breaks Order)
Currently, both `commute_ppr` and `merge_ppr_ppm` use the `sortTopologically` function to sort a range of operations in said block in topological order. 

However, this approach will lead to a problem where one of nullary operation (e.g. `quantum.device_release`) is reorder incorrectly (should not move). 

Example:  `test.mlir`
```mlir
func.func @test_commute_1(%q1 : !quantum.bit){
    %100 = arith.constant 100 : i64
    quantum.device shots(%100) ["librtd_null_qubit.dylib", "NullQubit", "{'track_resources': False}"]
    %0 = qec.ppr ["Z"](4) %q1 : !quantum.bit
    %1 = qec.ppr ["Z"](8) %0 : !quantum.bit
    %2 = qec.ppr ["Z"](4) %1 : !quantum.bit
    quantum.device_release
    func.return
}
```
After perform `quantum-opt --commute-ppr test.mlir`, we got:

```mlir
  func.func @test_commute_1(%arg0: !quantum.bit) {
    %0 = qec.ppr ["Z"](8) %arg0 : !quantum.bit
    quantum.device_release
    %1 = qec.ppr ["Z"](8) %0 : !quantum.bit
    %2 = qec.ppr ["Z"](8) %1 : !quantum.bit
    return
  }
```

`quantum.device_release` should not be moved to the top.

**Proposed solution:**
- set the list of operation that needed to order in `isOperandReady` in `sortTopologically`. 

**This is not only solve the problem, but also reduce the sorting time as well.**

### PR DESCRIPTION
**Pull request by sengthai**
Fix `commute_ppr` and `merge_ppr_ppm` to handle nullary operations correctly and improve compilation time

- Updated `commute_ppr` and `merge_ppr_ppm` to prevent incorrect movement of nullary operations.
- Enhanced the sorting mechanism to optimize compilation time by reducing unnecessary sorting operations.
- Added relevant test cases to ensure correctness of the changes.

Related GitHub Issue:
Fixes #2194
[sc-104020]

### CODE REVIEW

File: mlir/lib/QEC/Transforms/CommutePPR.cpp [hunk 1]
```diff
@@ -12,6 +12,9 @@
 // See the License for the specific language governing permissions and
 // limitations under the License.
 
+#include <llvm/ADT/iterator_range.h>
+#include <llvm/Support/Casting.h>
+#include <mlir/IR/Operation.h>
```
Comment (dime10) [inline mlir/lib/QEC/Transforms/CommutePPR.cpp]: Please combine these with existing imports below the debug type :)

File: mlir/lib/QEC/Transforms/CommutePPR.cpp [hunk 2]
```diff
@@ -136,6 +139,12 @@ void moveCliffordPastNonClifford(const PauliStringWrapper &lhsPauli,
     }
 
     rewriter.replaceOp(rhs, rhs.getInQubits());
+
+    auto startItr = lhs->getIterator();
+    auto endItr = std::next(nonCliffordOp->getIterator());
+    llvm::iterator_range<Block::iterator> itr = llvm::make_range(startItr, endItr);
+
+    sortTopologically(nonCliffordOp->getBlock(), itr);
```
Comment (dime10) [inline mlir/lib/QEC/Transforms/CommutePPR.cpp:144]: Nice! If possible, I would love if we could run this through ASAN just to make sure we don't have any memory issues.

File: mlir/lib/QEC/Transforms/CommutePPR.cpp (hunk 1 above)
Comment (sengthai) [reply mlir/lib/QEC/Transforms/CommutePPR.cpp]: Sure thing~

File: mlir/lib/QEC/Transforms/CommutePPR.cpp (hunk 2 above)
Comment (sengthai) [reply mlir/lib/QEC/Transforms/CommutePPR.cpp:144]: Thanks @dime10~ Just confirm that with `ENABLE_ASAN=ON`, the tests work well.

Comment (sengthai) [reply mlir/lib/QEC/Transforms/CommutePPR.cpp:144]: However, I did not pass other tests then ASAN is on. I also try to test on main branch, and got the same failure. 🤔
```
Failed Tests (14):
  Compiler test suite :: Gradient/AdjointTest.mlir
  Compiler test suite :: Gradient/ClassicalJacobianTest.mlir
  Compiler test suite :: Gradient/CleanupFunctions.mlir
  Compiler test suite :: Gradient/FiniteDifferenceTest.mlir
  Compiler test suite :: Gradient/HybridGradientTest.mlir
  Compiler test suite :: Gradient/JVPTest.mlir
  Compiler test suite :: Gradient/PS_FunctionShiftingTest.mlir
  Compiler test suite :: Gradient/PS_QuantumGradientTest.mlir
  Compiler test suite :: Gradient/ParameterShiftTest.mlir
  Compiler test suite :: Gradient/StaticAllocaTest.mlir
  Compiler test suite :: Gradient/VJPTest.mlir
  Compiler test suite :: QEC/TLayerReduction.mlir
  Compiler test suite :: cli/DumpPipeline.mlir
  Compiler test suite :: cli/DumpTiming.mlir
  ```

Comment (dime10) [reply mlir/lib/QEC/Transforms/CommutePPR.cpp:144]: Thank you for checking it! It's possible we've accumulated some ASAN errors since they are not run automatically.. but at least this test is passing. Thanks!

File: doc/releases/changelog-dev.md [hunk 3]
```diff
@@ -106,6 +106,11 @@
   // ... use %4
   ```
 
+  * Fixes :func:`~.passes.commute_ppr` and :func:`~.passes.merge_ppr_ppm` incorrectly
+    moving nullary operations. This also improves the compilation time by reducing
+    the sort function, given the operations that need to be sorted.
```
Comment (paul0403) [inline doc/releases/changelog-dev.md]:
```suggestion
    the sort function, by explicitly passing the operations that need to be sorted.
```
