### PR TITLE
[MLIR] Improve buffer deallocation by inlining functions

### LINKED ISSUE #64: [MLIR] Dialect `complex' not found for custom op 'complex.constant'
Consider the following program running Catalyst `0.1.0` and PennyLane `0.28`:

``` python
import pennylane as qml
import jax.numpy as jnp
from catalyst import qjit

@qjit
def workflow(params):
    @qml.qnode(qml.device("lightning.qubit", wires=1),)
    def circuit(phi):
        qml.PhaseShift(phi=phi, wires=[0])
        return qml.state()

    phi = params[0]
    for _ in range(10):
        state = circuit(phi)[0]
        phi = jnp.mean(state).real
        # phi = (state[0] + state[1])/2).real       # In contrast, this approach works
    return state

print(workflow(jnp.array([jnp.pi], dtype=jnp.float64)))
```

An attempt to run the program results in the following compilation error. Other expressions involving complex/float computations seem to cause similar errors.

```
/tmp/tmpkjcy955a/workflow.nohlo.mlir:6:12: error: Dialect `complex' not found for custom op 'complex.constant'
    %cst = complex.constant [0.000000e+00, 0.000000e+00] : complex<f64>
           ^
/tmp/tmpkjcy955a/workflow.nohlo.mlir:6:12: note: Registered dialects: arith, builtin, func, gradient, index, linalg, llvm, memref, quantum, scf, tensor ; for more info on dialect registration see https://mlir.llvm.org/getting_started/Faq/#registered-loaded-dependent-whats-up-with-dialects-management
Traceback (most recent call last):
  File "/home/sergei/complex_dialiect_issue.py", line 18, in <module>
    print(workflow(jnp.array([jnp.pi], dtype=jnp.float64)))
  File "/home/sergei/.local/lib/python3.8/site-packages/catalyst/compilation_pipelines.py", line 611, in __call__
    self.compiled_function = self.compile()
  File "/home/sergei/.local/lib/python3.8/site-packages/catalyst/compilation_pipelines.py", line 585, in compile
    shared_object, self._llvmir = compiler.compile(
  File "/home/sergei/.local/lib/python3.8/site-packages/catalyst/compiler.py", line 318, in compile
    buff = bufferize_tensors(mlir)
  File "/home/sergei/.local/lib/python3.8/site-packages/catalyst/compiler.py", line 195, in bufferize_tensors
    subprocess.run(command, stdout=file, check=True)
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/sergei/.local/lib/python3.8/site-packages/catalyst/bin/quantum-opt', '/tmp/tmpkjcy955a/workflow.nohlo.mlir', '--lower-gradients', '--gradient-bufferize', '--scf-bufferize', '--convert-tensor-to-linalg', '--convert-elementwise-to-linalg', '--arith-bufferize', '--empty-tensor-to-alloc-tensor', '--bufferization-bufferize', '--tensor-bufferize', '--linalg-bufferize', '--tensor-bufferize', '--quantum-bufferize', '--func-bufferize', '--finalizing-bufferize', '--buffer-hoisting', '--convert-bufferization-to-memref', '--canonicalize', '--cse']' returned non-zero exit status 1.
```

### PR DESCRIPTION
**Pull request by dime10**
This change makes buffer-deallocation much more effective since the pass cannot deallocate buffers across function boundaries.
Inlining could also be used to make other passes more effective, such folding, cse, and other standard optimizations.

Currently, inlining gradient operations is supported, while inlining quantum functions is not (can easily be enabled by implementing the `DialectInlinerInterface`). I'm not yet sure about the pros/cons of doing so.

Fixes #64

### CODE REVIEW

File: mlir/lib/Gradient/IR/GradientDialect.cpp [hunk 1]
```diff
@@ -20,6 +22,23 @@ using namespace catalyst::gradient;
 
 #include "Gradient/IR/GradientOpsDialect.cpp.inc"
 
+//===----------------------------------------------------------------------===//
+// Complex Dialect Interfaces
```
Comment (maliasadi) [inline mlir/lib/Gradient/IR/GradientDialect.cpp:26]: "Complex" :) What about,
```suggestion
// Interfaces.
```

File: mlir/tools/quantum-opt/quantum-opt.cpp [hunk 2]
```diff
@@ -33,21 +33,9 @@ int main(int argc, char **argv)
...
-    registry.insert<mlir::func::FuncDialect>();
-    registry.insert<mlir::arith::ArithDialect>();
-    registry.insert<mlir::scf::SCFDialect>();
-    registry.insert<mlir::LLVM::LLVMDialect>();
-    registry.insert<mlir::memref::MemRefDialect>();
-    registry.insert<mlir::tensor::TensorDialect>();
-    registry.insert<mlir::linalg::LinalgDialect>();
-    registry.insert<mlir::index::IndexDialect>();
-    registry.insert<mlir::bufferization::BufferizationDialect>();
+    mlir::registerAllDialects(registry);
```
Comment (maliasadi) [inline mlir/tools/quantum-opt/quantum-opt.cpp:36]: How would it affect the binary size of the tool and catalyst wheels in general? :thinking: 

It's indeed fixing issue #64 by registering all built-in dialects.

**Review by maliasadi — CHANGES_REQUESTED** [review]
Thanks @dime10! It's nice to see the buffer deallocation improvement. It would be also interesting to check the impacts of using the `inline` pass on code size and compilation time of hybrid programs.

File: doc/changelog.md [hunk 3]
```diff
@@ -22,6 +22,9 @@
   [MLIR bufferization infrastructure](https://mlir.llvm.org/docs/Bufferization/).
   [#63](https://github.com/PennyLaneAI/catalyst/pull/63)
 
+* Perform function inlining to improve optimizations and memory management within the compiler.
```
[the remark this answers is not in the document]
Comment (dime10) [reply doc/changelog.md:25]: The inlining is not specific to gradient operations, so function inlining is more appropriate here :)

File: frontend/catalyst/compiler.py [hunk 4]
```diff
@@ -258,6 +262,30 @@ def lower_mhlo_to_linalg(filename):
...
+def transform_quantum_ir(filename):
+    """Runs quantum optimizations and transformations, as well gradient transforms, on the hybrid
+    IR.
+
+    Args:
+        filename (str): the path to a file were the program is stored.
+    Returns:
+        a path to the output file
+    """
+    if filename[-5:] != ".mlir":
```
[the remark this answers is not in the document]
Comment (dime10) [reply frontend/catalyst/compiler.py:274]: We don't use `os.extsep` anywhere else, and in particular we don't use it when we generate the file names.

I'm not opposed to using it in general, but it would have to be consistent (see the [discussion here](https://github.com/PennyLaneAI/catalyst/pull/67#discussion_r1145368377)).

File: frontend/catalyst/compiler.py [hunk 5]
```diff
@@ -66,8 +66,12 @@ def get_lib_path(project, env):
...
-bufferization_pass_pipeline = [
+quantum_compilation_pass_pipeline = [
     "--lower-gradients",
+]
+
+bufferization_pass_pipeline = [
+    "--inline",
     "--gradient-bufferize",
     "--scf-bufferize",
     "--convert-tensor-to-linalg",  # tensor.pad
```
[the remark this answers is not in the document]
Comment (dime10) [reply frontend/catalyst/compiler.py:77]: I think you misunderstood, `--inline` is a general inlining pass that inserts the body of an mlir function (from the function dialect) into a function call, independant of dialects. However, this behaviour is opt-in not opt-out, that is dialects have to declare which of their operations are legal to inline in what circumstances. The `DialectInlinerInterface` exists for this reason, and is implemented for most standard mlir dialects. I also implemented it for the gradient dialect so functions containing gradient ops wouldn't be excluded from being inlined. I explicitly didn't implement it for the quantum dialect (for now), in order to keep the separation between classical and quantum functions.

During my testing I also realized that index and complex dialect operations were preventing some functions in our user code from being inlined, and I've already submitted a patch for it upstream: https://reviews.llvm.org/D147064

File: mlir/lib/Gradient/IR/GradientDialect.cpp (hunk 1 above)
Comment (dime10) [reply mlir/lib/Gradient/IR/GradientDialect.cpp:26]: Ah thanks, copy paste mistake 😅

File: mlir/tools/quantum-opt/quantum-opt.cpp (hunk 2 above)
Comment (dime10) [reply mlir/tools/quantum-opt/quantum-opt.cpp:36]: I don't think binary size would change, since the dialects are still present in the tool (we can and have always been able to generate and manipulate ops from all those dialects, what this does is allow all those dialects to be parsed from an `.mlir` input file). But I haven't verified this.

File: frontend/catalyst/compiler.py [hunk 6]
```diff
@@ -395,11 +423,13 @@ def compile(mlir_module, workspace, passes):
     with open(filename, "w", encoding="utf-8") as f:
         mlir_module.operation.print(f, print_generic_op_form=False, assume_verified=True)
 
-    passes["mlir"] = filename
     mlir = filename
```
[the remark this answers is not in the document]
Comment (dime10) [reply frontend/catalyst/compiler.py:426]: Just wanted to keep the structure consistent here :)

File: frontend/catalyst/compiler.py [hunk 7]
```diff
@@ -395,11 +423,13 @@ def compile(mlir_module, workspace, passes):
...
-    mlir = lower_mhlo_to_linalg(mlir)
-    passes["nohlo"] = mlir
-    buff = bufferize_tensors(mlir)
+    passes["mlir"] = filename
```
Comment (dime10) [inline frontend/catalyst/compiler.py:427]:
```suggestion
    passes["mlir"] = mlir
```

File: mlir/lib/Gradient/IR/GradientDialect.cpp [hunk 8]
```diff
@@ -20,6 +22,23 @@ using namespace catalyst::gradient;
...
+
+namespace {
+struct GradientInlinerInterface : public DialectInlinerInterface {
+    using DialectInlinerInterface::DialectInlinerInterface;
+
+    /// Operations in Gradient dialect are always legal to inline.
+    bool isLegalToInline(Operation *, Region *, bool,
+                         BlockAndValueMapping &valueMapping) const final
+    {
+        return true;
```
Comment (erick-xanadu) [inline mlir/lib/Gradient/IR/GradientDialect.cpp:37]: Quick question about the inlining interface used here. If `isLegalToInline` returns true for a particular function, does this mean that that function will be inlined at all its callsites? Or will it mean that `isLegalToInline` will turn them into a candidate for inlining that still needs to undergo a profitability heuristic? If it is the second one, do you know what profitability heuristic is used?

**Review by erick-xanadu — APPROVED** [review]

File: mlir/lib/Gradient/IR/GradientDialect.cpp (hunk 8 above)
Comment (erick-xanadu) [reply mlir/lib/Gradient/IR/GradientDialect.cpp:37]: Cool, happy to approve.

File: frontend/catalyst/compiler.py (hunk 4 above)
[the remark this answers is not in the document]
Comment (maliasadi) [reply frontend/catalyst/compiler.py:274]: Ah! I thought that PR #68  is already merged. This update was originally addressed there. Nevermind :)

**Review by maliasadi — APPROVED** [review]
