### PR TITLE
[MLIR] Fix adjoint lowering pass

### LINKED ISSUE #589: Compiler error when nesting `adjoint` and `ctrl`
#### Issue description

* *Expected behavior:* `ctrl` and `adjoint` can be nested and chained with no errors.

* *Actual behavior:* Performing the adjoint of subroutine that contains adjoints of controlled controlled operations (sorry!) throws an error like this one:

```
python: /__w/catalyst/catalyst/mlir/llvm-project/mlir/include/mlir/IR/IRMapping.h:74: auto mlir::IRMapping::lookup(T) const [with T = mlir::Value]: Assertion `result && "expected 'from' to be contained within the map"' failed.
[1]    111211 IOT instruction (core dumped)  python bug.py
```

* *Reproduces how often:* Always, but only when we call a subroutine before we call its adjointed controlled version.

* *System information:* (post the output of `import pennylane as qml; qml.about()`)

```
Name: PennyLane
Version: 0.35.0
Summary: PennyLane is a cross-platform Python library for quantum computing, quantum machine learning, and quantum chemistry. Train a quantum computer the same way as a neural network.
Home-page: https://github.com/PennyLaneAI/pennylane
Author: 
Author-email: 
License: Apache License 2.0
Location: /home/olivia/.conda/envs/shortalyst/lib/python3.12/site-packages
Requires: appdirs, autograd, autoray, cachetools, networkx, numpy, pennylane-lightning, requests, rustworkx, scipy, semantic-version, toml, typing-extensions
Required-by: PennyLane-Catalyst, PennyLane_Lightning

Platform info:           Linux-6.5.0-21-generic-x86_64-with-glibc2.35
Python version:          3.12.2
Numpy version:           1.26.4
Scipy version:           1.12.0
Installed devices:
- lightning.qubit (PennyLane_Lightning-0.35.0)
- nvidia.custatevec (PennyLane-Catalyst-0.5.0)
- nvidia.cutensornet (PennyLane-Catalyst-0.5.0)
- softwareq.qpp (PennyLane-Catalyst-0.5.0)
- default.clifford (PennyLane-0.35.0)
- default.gaussian (PennyLane-0.35.0)
- default.mixed (PennyLane-0.35.0)
- default.qubit (PennyLane-0.35.0)
- default.qubit.autograd (PennyLane-0.35.0)
- default.qubit.jax (PennyLane-0.35.0)
- default.qubit.legacy (PennyLane-0.35.0)
- default.qubit.tf (PennyLane-0.35.0)
- default.qubit.torch (PennyLane-0.35.0)
- default.qutrit (PennyLane-0.35.0)
- null.qubit (PennyLane-0.35.0)
None
```

#### Source code and tracebacks

The smallest example I can produce is 

```python
import pennylane as qml
from catalyst import adjoint, ctrl, qjit

def subsubroutine():
    ctrl(qml.PhaseShift, control=2)(0.1, wires=3)
    

def subroutine():
    # If either of the two lines below are commented, there is no error. Only when both run.
    subsubroutine() 
    adjoint(ctrl(subsubroutine, control=0))()

dev = qml.device("lightning.qubit", wires=4, shots=500)

@qjit()
@qml.qnode(dev)
def circuit():
    adjoint(subroutine)()
    return qml.probs(wires=dev.wires)

print(circuit())
```

### PR DESCRIPTION
**Pull request by erick-xanadu**
**Context:** It looks like adjoint was not correctly taking into account all wires in control operations.

**Description of the Change:** Modifies the adjoint lowering pass to take into account all wires in control operations

**Benefits:** Fixes #589 

**Related GitHub Issues:** #589

### CODE REVIEW

**Comment by grwlf** [comment]
Thanks, Erick. I did feel something wrong about these lines)

**Review by grwlf — APPROVED** [review]

File: mlir/lib/Quantum/Transforms/AdjointPatterns.cpp [hunk 1]
```diff
@@ -265,7 +265,7 @@ class AdjointGenerator {
         }
 
         for (const auto &[qubitResult, qubitOperand] :
-             llvm::zip(clone.getNonCtrlQubitResults(), gate.getNonCtrlQubitOperands())) {
+             llvm::zip(clone.getQubitResults(), gate.getQubitOperands())) {
```
Comment (glassnotes) [inline mlir/lib/Quantum/Transforms/AdjointPatterns.cpp:268]: This is a very satisfying 1-line fix for what looked like a super obscure error :laughing: Thanks so much!

Comment (erick-xanadu) [reply mlir/lib/Quantum/Transforms/AdjointPatterns.cpp:268]: Happy to help! And thanks for the bug report :)
