### PR TITLE
Fix cli hang

### LINKED ISSUE #2411: `catalyst` CLI tool hangs without input file
# Issue
When calling `catalyst --list-passes` I noticed that the command hangs rather than perform the desired action. This happens as well when called directly with `catalyst`. When provided an input file (`catalyst --list-passes test.mlir`), the command runs but the file is optimized and no passes are listed. This makes the pass list inaccessible via the `catalyst` utility.

# Expected behaviour
I would expect behaviour similar to `quantum-opt`, which when called directly listens to `stdin` for mlir to process, or an error to be raised.

# MRE
`./mlir/build/bin/catalyst` from project root.

### PR DESCRIPTION
**Pull request by kipawaa**
**Context:**
the `catalyst` cli tool was silently listening to stdin when not provided an input file, regardless of CLI arguments except for help.

**Description of the Change:**
This adds a message before listening to stdin, and moves the listening to after parsing other flags like `--list-passes` and `--show-dialects`.

**Benefits:**
`catalyst` works as advertised!

**Possible Drawbacks:**
N/A

**Related GitHub Issues:**
Closes #2411

### CODE REVIEW

**Review by mehrdad2m — APPROVED** [review]
LGTM

**Review by lazypanda10117 — APPROVED** [review]

File: mlir/lib/Driver/CompilerDriver.cpp [hunk 1]
```diff
@@ -560,6 +560,7 @@ LogicalResult runEnzymePasses(const CompilerOptions &options,
 std::string readInputFile(const std::string &filename)
 {
     if (filename == "-") {
```
Comment (mehrdad2m) [inline mlir/lib/Driver/CompilerDriver.cpp:562]:
```suggestion
    if (filename == "-" && llvm::errs().is_displayed()) {
```
I am wondering if we could do something like this? If it works, it would be a more systematic fix.

Comment (mehrdad2m) [reply mlir/lib/Driver/CompilerDriver.cpp:562]: inspired by https://github.com/llvm/llvm-project/blob/113f01aa82d055410f22a9d03b3468fa68600589/clang-tools-extra/clangd/tool/ClangdMain.cpp#L869-L874

Comment (kipawaa) [reply mlir/lib/Driver/CompilerDriver.cpp:562]: Great find! I like this much better 💯 added in [fb8d9d2](https://github.com/PennyLaneAI/catalyst/pull/2447/commits/fb8d9d2e6705bb4b3f22695f7d294bcdf3ef1c66) and removed the hack in mlir-graph

**Review by mehrdad2m — APPROVED** [review]
